apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque    # default for arbitrary key-value pairs, others could be TLS certificate
data:           # you can name the username and password key whatever you want
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
  
# The values in key-value pairs are not plaintext, they are in base-64.
# You can do this in the terminal to get base-64: "echo -n 'username' | base64"
# Storing the data in a Secret component doesn't automatically make it secure.
# There are built-in mechanism (e.g., encryption) for basic security, which are not enable by default.
